# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\GIT\DispFilter\DispFilterGUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DispFilter(object):
    def setupUi(self, DispFilter):
        DispFilter.setObjectName("DispFilter")
        DispFilter.resize(380, 440)
        DispFilter.setMinimumSize(QtCore.QSize(380, 440))
        DispFilter.setMaximumSize(QtCore.QSize(380, 440))
        self.centralwidget = QtWidgets.QWidget(DispFilter)
        self.centralwidget.setObjectName("centralwidget")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(181, -5, 12, 65))
        self.line_2.setMaximumSize(QtCore.QSize(12, 65))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(1, 55, 380, 12))
        self.line.setMaximumSize(QtCore.QSize(380, 12))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.CB_ListLPU = QtWidgets.QComboBox(self.centralwidget)
        self.CB_ListLPU.setGeometry(QtCore.QRect(6, 18, 174, 24))
        self.CB_ListLPU.setMinimumSize(QtCore.QSize(174, 24))
        self.CB_ListLPU.setMaximumSize(QtCore.QSize(174, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CB_ListLPU.setFont(font)
        self.CB_ListLPU.setObjectName("CB_ListLPU")
        self.CB_ListLPU.addItem("")
        self.CB_ListLPU.addItem("")
        self.CB_ListLPU.addItem("")
        self.CB_ListLPU.addItem("")
        self.CB_ListLPU.addItem("")
        self.CB_ListLPU.addItem("")
        self.CB_ListLPU.addItem("")
        self.CB_ListLPU.addItem("")
        self.CB_ListLPU.addItem("")
        self.CB_ListLPU.addItem("")
        self.RB_Type_Prof = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_Type_Prof.setGeometry(QtCore.QRect(192, 32, 180, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RB_Type_Prof.setFont(font)
        self.RB_Type_Prof.setObjectName("RB_Type_Prof")
        self.RB_Type_Disp = QtWidgets.QRadioButton(self.centralwidget)
        self.RB_Type_Disp.setEnabled(True)
        self.RB_Type_Disp.setGeometry(QtCore.QRect(192, 6, 127, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.RB_Type_Disp.setFont(font)
        self.RB_Type_Disp.setChecked(True)
        self.RB_Type_Disp.setObjectName("RB_Type_Disp")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 164, 372, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_MIS = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_MIS.setFont(font)
        self.label_MIS.setObjectName("label_MIS")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_MIS)
        self.lineEdit_MIS = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_MIS.setMinimumSize(QtCore.QSize(328, 24))
        self.lineEdit_MIS.setMaximumSize(QtCore.QSize(328, 24))
        self.lineEdit_MIS.setObjectName("lineEdit_MIS")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit_MIS)
        self.TButton_MIS = QtWidgets.QToolButton(self.layoutWidget)
        self.TButton_MIS.setMinimumSize(QtCore.QSize(32, 24))
        self.TButton_MIS.setMaximumSize(QtCore.QSize(32, 24))
        self.TButton_MIS.setObjectName("TButton_MIS")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TButton_MIS)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.progressBar_MIS = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar_MIS.setMinimumSize(QtCore.QSize(0, 24))
        self.progressBar_MIS.setMaximumSize(QtCore.QSize(210, 24))
        font = QtGui.QFont()
        font.setKerning(True)
        self.progressBar_MIS.setFont(font)
        self.progressBar_MIS.setProperty("value", 0)
        self.progressBar_MIS.setTextVisible(False)
        self.progressBar_MIS.setFormat("")
        self.progressBar_MIS.setObjectName("progressBar_MIS")
        self.horizontalLayout_2.addWidget(self.progressBar_MIS)
        self.Count_Sum_MIS = QtWidgets.QLineEdit(self.layoutWidget)
        self.Count_Sum_MIS.setEnabled(True)
        self.Count_Sum_MIS.setMinimumSize(QtCore.QSize(40, 24))
        self.Count_Sum_MIS.setMaximumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Count_Sum_MIS.setFont(font)
        self.Count_Sum_MIS.setStyleSheet("background-color: rgb(219, 217, 255);")
        self.Count_Sum_MIS.setAlignment(QtCore.Qt.AlignCenter)
        self.Count_Sum_MIS.setReadOnly(True)
        self.Count_Sum_MIS.setObjectName("Count_Sum_MIS")
        self.horizontalLayout_2.addWidget(self.Count_Sum_MIS)
        self.Button_Calculate_MIS = QtWidgets.QPushButton(self.layoutWidget)
        self.Button_Calculate_MIS.setMinimumSize(QtCore.QSize(100, 24))
        self.Button_Calculate_MIS.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Calculate_MIS.setFont(font)
        self.Button_Calculate_MIS.setObjectName("Button_Calculate_MIS")
        self.horizontalLayout_2.addWidget(self.Button_Calculate_MIS)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(6, 66, 372, 89))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label_OMS = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_OMS.setFont(font)
        self.label_OMS.setObjectName("label_OMS")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_OMS)
        self.lineEdit_OMS = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_OMS.setMinimumSize(QtCore.QSize(328, 24))
        self.lineEdit_OMS.setMaximumSize(QtCore.QSize(328, 24))
        self.lineEdit_OMS.setObjectName("lineEdit_OMS")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit_OMS)
        self.TButton_OMS = QtWidgets.QToolButton(self.layoutWidget1)
        self.TButton_OMS.setMinimumSize(QtCore.QSize(32, 24))
        self.TButton_OMS.setMaximumSize(QtCore.QSize(32, 24))
        self.TButton_OMS.setObjectName("TButton_OMS")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.TButton_OMS)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar_OMS = QtWidgets.QProgressBar(self.layoutWidget1)
        self.progressBar_OMS.setMinimumSize(QtCore.QSize(0, 24))
        self.progressBar_OMS.setMaximumSize(QtCore.QSize(210, 24))
        font = QtGui.QFont()
        font.setKerning(True)
        self.progressBar_OMS.setFont(font)
        self.progressBar_OMS.setProperty("value", 0)
        self.progressBar_OMS.setTextVisible(False)
        self.progressBar_OMS.setFormat("")
        self.progressBar_OMS.setObjectName("progressBar_OMS")
        self.horizontalLayout.addWidget(self.progressBar_OMS)
        self.Count_Sum_OMS = QtWidgets.QLineEdit(self.layoutWidget1)
        self.Count_Sum_OMS.setEnabled(True)
        self.Count_Sum_OMS.setMinimumSize(QtCore.QSize(40, 24))
        self.Count_Sum_OMS.setMaximumSize(QtCore.QSize(40, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Count_Sum_OMS.setFont(font)
        self.Count_Sum_OMS.setAutoFillBackground(False)
        self.Count_Sum_OMS.setStyleSheet("background-color: rgb(255, 219, 220);")
        self.Count_Sum_OMS.setAlignment(QtCore.Qt.AlignCenter)
        self.Count_Sum_OMS.setReadOnly(True)
        self.Count_Sum_OMS.setObjectName("Count_Sum_OMS")
        self.horizontalLayout.addWidget(self.Count_Sum_OMS)
        self.Button_Calculate_OMS = QtWidgets.QPushButton(self.layoutWidget1)
        self.Button_Calculate_OMS.setMinimumSize(QtCore.QSize(100, 24))
        self.Button_Calculate_OMS.setMaximumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Calculate_OMS.setFont(font)
        self.Button_Calculate_OMS.setObjectName("Button_Calculate_OMS")
        self.horizontalLayout.addWidget(self.Button_Calculate_OMS)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lineEdit_Error = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Error.setGeometry(QtCore.QRect(9, 306, 328, 24))
        self.lineEdit_Error.setMinimumSize(QtCore.QSize(328, 24))
        self.lineEdit_Error.setMaximumSize(QtCore.QSize(328, 24))
        self.lineEdit_Error.setPlaceholderText("")
        self.lineEdit_Error.setObjectName("lineEdit_Error")
        self.label_Error = QtWidgets.QLabel(self.centralwidget)
        self.label_Error.setGeometry(QtCore.QRect(9, 274, 337, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_Error.setFont(font)
        self.label_Error.setObjectName("label_Error")
        self.TButton_Error = QtWidgets.QToolButton(self.centralwidget)
        self.TButton_Error.setGeometry(QtCore.QRect(343, 306, 32, 24))
        self.TButton_Error.setMinimumSize(QtCore.QSize(32, 24))
        self.TButton_Error.setMaximumSize(QtCore.QSize(32, 24))
        self.TButton_Error.setObjectName("TButton_Error")
        self.Button_Result = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Result.setGeometry(QtCore.QRect(292, 342, 84, 63))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Result.sizePolicy().hasHeightForWidth())
        self.Button_Result.setSizePolicy(sizePolicy)
        self.Button_Result.setMinimumSize(QtCore.QSize(84, 63))
        self.Button_Result.setMaximumSize(QtCore.QSize(84, 63))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Result.setFont(font)
        self.Button_Result.setObjectName("Button_Result")
        self.Count_Sum_Errors = QtWidgets.QLineEdit(self.centralwidget)
        self.Count_Sum_Errors.setEnabled(True)
        self.Count_Sum_Errors.setGeometry(QtCore.QRect(156, 343, 44, 24))
        self.Count_Sum_Errors.setMinimumSize(QtCore.QSize(44, 24))
        self.Count_Sum_Errors.setMaximumSize(QtCore.QSize(44, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Count_Sum_Errors.setFont(font)
        self.Count_Sum_Errors.setAlignment(QtCore.Qt.AlignCenter)
        self.Count_Sum_Errors.setReadOnly(True)
        self.Count_Sum_Errors.setObjectName("Count_Sum_Errors")
        self.Button_Open_Result = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Open_Result.setGeometry(QtCore.QRect(206, 342, 78, 26))
        self.Button_Open_Result.setMinimumSize(QtCore.QSize(78, 26))
        self.Button_Open_Result.setMaximumSize(QtCore.QSize(78, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Open_Result.setFont(font)
        self.Button_Open_Result.setObjectName("Button_Open_Result")
        self.Button_Save_Result = QtWidgets.QPushButton(self.centralwidget)
        self.Button_Save_Result.setGeometry(QtCore.QRect(206, 378, 78, 26))
        self.Button_Save_Result.setMinimumSize(QtCore.QSize(78, 26))
        self.Button_Save_Result.setMaximumSize(QtCore.QSize(78, 26))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Button_Save_Result.setFont(font)
        self.Button_Save_Result.setObjectName("Button_Save_Result")
        self.label_Found_Errors = QtWidgets.QLabel(self.centralwidget)
        self.label_Found_Errors.setGeometry(QtCore.QRect(10, 342, 127, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.label_Found_Errors.setFont(font)
        self.label_Found_Errors.setObjectName("label_Found_Errors")
        DispFilter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DispFilter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        DispFilter.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(DispFilter)
        QtCore.QMetaObject.connectSlotsByName(DispFilter)

    def retranslateUi(self, DispFilter):
        _translate = QtCore.QCoreApplication.translate
        DispFilter.setWindowTitle(_translate("DispFilter", "MainWindow"))
        self.CB_ListLPU.setItemText(0, _translate("DispFilter", "514 - Поликлиника №1"))
        self.CB_ListLPU.setItemText(1, _translate("DispFilter", "512 - Поликлиника №2"))
        self.CB_ListLPU.setItemText(2, _translate("DispFilter", "523 - Поликлиника №3"))
        self.CB_ListLPU.setItemText(3, _translate("DispFilter", "518 - Поликлиника №4"))
        self.CB_ListLPU.setItemText(4, _translate("DispFilter", "502 - Терсинская пол-ка"))
        self.CB_ListLPU.setItemText(5, _translate("DispFilter", "522 - Колоярская амб."))
        self.CB_ListLPU.setItemText(6, _translate("DispFilter", "532 - Барановская амб."))
        self.CB_ListLPU.setItemText(7, _translate("DispFilter", "552 - Н.Чернавская амб."))
        self.CB_ListLPU.setItemText(8, _translate("DispFilter", "582 - Черкасская пол-ка"))
        self.CB_ListLPU.setItemText(9, _translate("DispFilter", "602 - Ш.Буеракская амб."))
        self.RB_Type_Prof.setText(_translate("DispFilter", "Профилактический осмотр"))
        self.RB_Type_Disp.setText(_translate("DispFilter", "Диспансеризация"))
        self.label_MIS.setText(_translate("DispFilter", "Выберите архив МИС"))
        self.lineEdit_MIS.setPlaceholderText(_translate("DispFilter", "Выберите Excel файл"))
        self.TButton_MIS.setText(_translate("DispFilter", "..."))
        self.Count_Sum_MIS.setPlaceholderText(_translate("DispFilter", "0"))
        self.Button_Calculate_MIS.setText(_translate("DispFilter", "Отфильтровать"))
        self.label_OMS.setText(_translate("DispFilter", "Выберите архив ОМС"))
        self.lineEdit_OMS.setPlaceholderText(_translate("DispFilter", "Выберите Excel файл"))
        self.TButton_OMS.setText(_translate("DispFilter", "..."))
        self.Count_Sum_OMS.setPlaceholderText(_translate("DispFilter", "0"))
        self.Button_Calculate_OMS.setText(_translate("DispFilter", "Отфильтровать"))
        self.label_Error.setText(_translate("DispFilter", "Место для сохранения архива ошибок"))
        self.TButton_Error.setText(_translate("DispFilter", "..."))
        self.Button_Result.setText(_translate("DispFilter", "Сравнить"))
        self.Count_Sum_Errors.setPlaceholderText(_translate("DispFilter", "0"))
        self.Button_Open_Result.setText(_translate("DispFilter", "Открыть"))
        self.Button_Save_Result.setText(_translate("DispFilter", "Сохранить"))
        self.label_Found_Errors.setText(_translate("DispFilter", "Найдено ошибок"))
        self.menuFile.setTitle(_translate("DispFilter", "Файл"))
        self.menu.setTitle(_translate("DispFilter", "Помощь"))
